[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.2.0",
    "flask-cors>=5.0.1",
    "flask>=3.1.1",
    "flask-sqlalchemy>=3.1.1",
    "gunicorn>=23.0.0",
    "httpx>=0.28.1",
    "psycopg2-binary>=2.9.10",
    "youtube-search-python>=1.6.6",
    "yt-dlp>=2025.4.30",
    "flask-limiter>=3.12",
    "trafilatura>=2.0.0",
    "pymongo>=4.12.1",
    "flask-login>=0.6.3",
    "flask-wtf>=1.2.2",
]
